services:
  db:
    container_name: postgres_$APP_NAME
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql

  redis:
    container_name: redis_$APP_NAME
    restart: unless-stopped
    image: redis:alpine
    command: redis-server --requirepass 123
    ports:
      - '6379:6379'

volumes:
  db: