from enum import StrEnum


class UserEventTypes(StrEnum):
    USER_CREATED = "USER_CREATED"
    USER_CONFIRMATION_SENT = "PASSWORD_CONFIRMATION_SENT"
    USER_CONFIRMED = "USER_CONFIRMED"
    USER_PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    USER_PASSWORD_RESET_CONFIRMED = "PASSWORD_RESET_CONFIRMED"
    USER_EMAIL_CHANGED = "EMAIL_CHANGED"
    USER_ARCHIVED = "USER_ARCHIVED"
